name: helm-package
on:
  push:
    branches:
    - master
    paths:
    - 'deploy/charts/oldmonk/**'
jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
        chmod 700 get_helm.sh
        ./get_helm.sh
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v1'
    - run: helm init --client-only
    - run: helm lint oldmonk/
      working-directory: deploy/charts/
  package:
    name: package
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v1'
    - run: helm package oldmonk/ --destination /github/home/pkg/
      working-directory: deploy/charts/
    - run: helm repo index oldmonk/ --destination /github/home/pkg/
      working-directory: deploy/charts/