name: helm-package
on:
  push:
    branches:
    - master
    paths:
    - 'deploy/charts/oldmonk/**'
jobs:
  release:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm init --client-only
        helm lint deploy/charts/oldmonk/
    - run: ls -la
    - run: mkdir output/
    - run: helm package deploy/charts/oldmonk/ -d output/
    - run: helm repo index output/ --merge deploy/charts/oldmonk/index.yaml
    - run: ls -la
    - run: mv output/* deploy/charts/oldmonk/
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: cc2b083ec53804405da2718e4befacccd7a450bd
        BRANCH: gh-pages 
        FOLDER: output