name: helm-package
on:
  push:
    branches:
    - master
    paths:
    - 'deploy/charts/oldmonk/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Helm
      run: |
        curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm init --client-only
    - name: Check sintax
      run: helm lint deploy/charts/oldmonk/
    - name: Create package
      run: |
        mkdir -p output/helm-charts/
        helm package deploy/charts/oldmonk/ -d output/helm-charts/
    - name: Reindex repo
      run: helm repo index output/helm-charts/
    - run: ls -la output/helm-charts/
    - run: cat output/helm-charts/index.yaml
    - name: Release
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: output/