name: helm-package
on:
  push:
    branches:
    - master
    paths:
    - 'deploy/charts/oldmonk/**'
jobs:
  release:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
        chmod 700 get_helm.sh
        ./get_helm.sh
    - uses: 'actions/checkout@v1'
    - run: helm init --client-only
    - run: helm lint oldmonk/
      working-directory: deploy/charts/
    - run: ls -la
    - run: helm package deploy/charts/oldmonk/
    - run: helm repo index oldmonk/ --url https://caiohasouza.github.io/test-oldmonk/deploy/charts/oldmonk/
    - run: ls -la
    - run: git push -u origin master