name: helm-package
on:
  push:
    branches:
    - master
    paths:
    - 'deploy/charts/oldmonk/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm init --client-only
    - run: helm lint deploy/charts/oldmonk/
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: ls -la 
    - run: mkdir -p output/helm-charts/
    - run: helm package deploy/charts/oldmonk/ -d output/helm-charts/
    - run: helm repo index output/helm-charts/ --merge deploy/charts/oldmonk/index.yaml
  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
    - run: ls -la
    - run: ls -la output/
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: cc2b083ec53804405da2718e4befacccd7a450bd
        BRANCH: gh-pages 
        FOLDER: output